select * 
from parks_and_recreation.employee_demographics ; # WE CAN USE OUR DATABASE NAME  LIKE HERE WHEN WE WILL BE HAVING MORE DATABASES AND WE NEED TO FIND THE PARTICULAR INFORMATION FROM A PARTICULAR DATABASE
# WE CAN DOUBLE CLICK ON THE DATABASE NAME TO SELECT IT FOR PERFORMING FUCNTIONS ON THAT DATABASE ONLY . 

# HERE WE ARE USING SELECT STATEMENT , SELECT * MEANS SELECTING THE ENTIRE TABLE BUT SELECT STATEMENT FOLLOWING WITH THE COLUMN NAMES MEANS WE ARE DISPLAYING ONLY THOSE PARTICULAR COLUMN DETAILS , IT CAN BE WRITTEN IN A ONE LINE BUT WRITNG IT IN DIFF LINE HELPS USER/PROGRAMMER TO IDENTIFY THE NAMES EASILY

select first_name , 
last_name , 
birth_date ,
age ,
age+10 ,# WE CAN ALSO PERFORM CALCULATIONS IN SELECT STATEMENT 
(age + 10 ) * 10 + 10
from parks_and_recreation.employee_demographics ;
# PEMDAS (PARANTHESIS , EXPONENTIAL , MULTI , DIV , ADD , SUB)

#DISTINCT IS USED TO SHOW ONLY THE UNIQUE VALUES PRESENT 

select distinct first_name  , gender 
from parks_and_recreation.employee_demographics ;

